version: "3"

services:
  community_forums_server:
    image: "postgres:14-alpine"
    ports:
      - "5441:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: community_forums_server_db
      POSTGRES_PASSWORD: community_forums_server_password
      POSTGRES_DB: community_forums_db
    volumes:
      - ./db-data/community_forums_server/:/var/lib/postgresql/data
